/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkAlchemicRouteImport } from './routes/work.alchemic'
import { Route as WorkFnpCircleRouteImport } from './routes/work.fnp-circle'
import { Route as WorkGigglesRouteImport } from './routes/work.giggles'
import { Route as WorkOnecareRouteImport } from './routes/work.onecare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAlchemicRoute = WorkAlchemicRouteImport.update({
  id: '/work/alchemic',
  path: '/work/alchemic',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFnpCircleRoute = WorkFnpCircleRouteImport.update({
  id: '/work/fnp-circle',
  path: '/work/fnp-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkGigglesRoute = WorkGigglesRouteImport.update({
  id: '/work/giggles',
  path: '/work/giggles',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOnecareRoute = WorkOnecareRouteImport.update({
  id: '/work/onecare',
  path: '/work/onecare',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/alchemic': typeof WorkAlchemicRoute
  '/work/fnp-circle': typeof WorkFnpCircleRoute
  '/work/giggles': typeof WorkGigglesRoute
  '/work/onecare': typeof WorkOnecareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/alchemic': typeof WorkAlchemicRoute
  '/work/fnp-circle': typeof WorkFnpCircleRoute
  '/work/giggles': typeof WorkGigglesRoute
  '/work/onecare': typeof WorkOnecareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/alchemic': typeof WorkAlchemicRoute
  '/work/fnp-circle': typeof WorkFnpCircleRoute
  '/work/giggles': typeof WorkGigglesRoute
  '/work/onecare': typeof WorkOnecareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/work/alchemic'
    | '/work/fnp-circle'
    | '/work/giggles'
    | '/work/onecare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/work/alchemic'
    | '/work/fnp-circle'
    | '/work/giggles'
    | '/work/onecare'
  id:
    | '__root__'
    | '/'
    | '/work/alchemic'
    | '/work/fnp-circle'
    | '/work/giggles'
    | '/work/onecare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkAlchemicRoute: typeof WorkAlchemicRoute
  WorkFnpCircleRoute: typeof WorkFnpCircleRoute
  WorkGigglesRoute: typeof WorkGigglesRoute
  WorkOnecareRoute: typeof WorkOnecareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/alchemic': {
      id: '/work/alchemic'
      path: '/work/alchemic'
      fullPath: '/work/alchemic'
      preLoaderRoute: typeof WorkAlchemicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/fnp-circle': {
      id: '/work/fnp-circle'
      path: '/work/fnp-circle'
      fullPath: '/work/fnp-circle'
      preLoaderRoute: typeof WorkFnpCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/giggles': {
      id: '/work/giggles'
      path: '/work/giggles'
      fullPath: '/work/giggles'
      preLoaderRoute: typeof WorkGigglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/onecare': {
      id: '/work/onecare'
      path: '/work/onecare'
      fullPath: '/work/onecare'
      preLoaderRoute: typeof WorkOnecareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkAlchemicRoute: WorkAlchemicRoute,
  WorkFnpCircleRoute: WorkFnpCircleRoute,
  WorkGigglesRoute: WorkGigglesRoute,
  WorkOnecareRoute: WorkOnecareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
